# docker run -it --rm -p 8080:8080 --device /dev/dri:/dev/dri  -v /home/sephirot/.lmstudio/models/:/models  -v $(pwd)/config.yaml:/etc/llama-swap/config/config.yaml  ghcr.io/mostlygeek/llama-swap:unified-vulkan

models:
  gemma31q4:
    cmd: llama-server --port ${PORT} --model /models/lmstudio-community/gemma-4-31B-it-GGUF/gemma-4-31B-it-Q4_K_M.gguf -md /models/lmstudio-community/gemma-4-31B-it-GGUF/gemma4-31B-it-assistant-Q4_K_M.gguf  --n-gpu-layers 999 --spec-type draft-mtp --spec-draft-n-max 2 --spec-draft-n-min 1 --ctx-size 262144 --host 0.0.0.0  --temp 0.1 --top-p 0.95 --top-k 64 --split-mode none --main-gpu 0 --flash-attn on --no-mmap -ngl 99 -ngld 99 --threads 8 --presence_penalty 0.0 --cache-type-k q4_0 --cache-type-v q4_0 --no-mmproj --parallel 1 
  # gemma31q6:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/gemma-4-31B-it-GGUF/gemma-4-31B-it-Q6_K.gguf -md /models/lmstudio-community/gemma-4-31B-it-GGUF/gemma4-31B-it-assistant-Q6_K_M.gguf --n-gpu-layers 999  --spec-type draft-mtp --spec-draft-n-max 2 --spec-draft-n-min 1 --ctx-size 262144 --host 0.0.0.0  --temp 0.1 --top-p 0.95 --top-k 64 --split-mode none --main-gpu 0 --flash-attn on --no-mmap -ngl 99 -ngld 99 --threads 8 --presence_penalty 0.0 --cache-type-k q4_0 --cache-type-v q4_0 --no-mmproj --parallel 1 
  # gemma31q8:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/gemma-4-31B-it-GGUF/gemma-4-31B-it-Q8_0.gguf -md /models/lmstudio-community/gemma-4-31B-it-GGUF/gemma4-31B-it-assistant-Q8_0.gguf --n-gpu-layers 999  --spec-type draft-mtp --spec-draft-n-max 2 --spec-draft-n-min 1 --ctx-size 262144 --host 0.0.0.0  --temp 0.1 --top-p 0.95 --top-k 64 --split-mode none --main-gpu 0 --flash-attn on --no-mmap -ngl 99 -ngld 99 --threads 8 --presence_penalty 0.0 --cache-type-k q4_0 --cache-type-v q4_0 --no-mmproj --parallel 1 
  # gemma31qat:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/gemma-4-31B-it-QAT-GGUF/gemma-4-31B-it-QAT-Q4_0.gguf --n-gpu-layers 999 --ctx-size 262144 --host 0.0.0.0 --temp 0.1 --parallel 1 --no-mmap -ngl 99 -ngld 99  --threads 16 --top-p 0.95 --top-k 64 --presence_penalty 0.0 --cache-type-k q8_0 --cache-type-v q8_0 --split-mode none --main-gpu 0 --flash-attn on
  gemma26:
    cmd: llama-server --port ${PORT} --model /models/lmstudio-community/gemma-4-26B-A4B-it-QAT-GGUF/gemma-4-26B-A4B-it-QAT-Q4_0.gguf -md /models/lmstudio-community/gemma-4-26B-A4B-it-QAT-GGUF/mtp-gemma-4-26B-A4B-it.gguf  --n-gpu-layers 999 --spec-type draft-mtp --spec-draft-n-max 2 --spec-draft-n-min 1 --ctx-size 131072 --host 0.0.0.0 --temp 1 --top-p 0.95 --top-k 64 --split-mode none --main-gpu 1 --flash-attn on --no-mmap -ngl 99 -ngld 99 --threads 8 --presence_penalty 0.0 --cache-type-k q4_0 --cache-type-v q4_0 --no-mmproj --parallel 1
  # gemma12q5:
  #   cmd: llama-server --port ${PORT} --model /models/unsloth/gemma-4-12b-it-GGUF/gemma-4-12b-it-Q5_K_M.gguf --ctx-size 131072 --host 0.0.0.0 --temp 1.0 --top-p 0.95 --top-k 64
  codestral-22b-q8:
    cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Codestral-22B-v0.1-GGUF/Codestral-22B-v0.1-Q8_0.gguf --n-gpu-layers 99 --ctx-size 16384 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64
  # qwen36-a3b-q4:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-Q4_K_M.gguf --n-gpu-layers 99 --ctx-size 8192 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64 --split-mode none --main-gpu 1
  # qwen36-a3b-q6:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-Q6_K.gguf --n-gpu-layers 99 --ctx-size 131072 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64
  # qwen36-a3b-q8:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-Q8_0.gguf --n-gpu-layers 99 --ctx-size 131072 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64
  # qwen36-27b-q4:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Qwen3.6-27B-GGUF/Qwen3.6-27B-Q4_K_M.gguf --n-gpu-layers 99 --ctx-size 131072 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64
  # qwen36-27b-q6:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Qwen3.6-27B-GGUF/Qwen3.6-27B-Q6_K.gguf --n-gpu-layers 99 --ctx-size 131072 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64
  # qwen36-27b-q8:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Qwen3.6-27B-GGUF/Qwen3.6-27B-Q8_0.gguf --n-gpu-layers 99 --ctx-size 131072 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64
  qwen36-27b-mtp-q3:
    cmd: llama-server --port ${PORT} --model /models/unsloth/Qwen3.6-27B-MTP-GGUF/Qwen3.6-27B-Q3_K_S.gguf --spec-type draft-mtp --spec-draft-n-max 2 --spec-draft-n-min 1 --ctx-size 16384 --n-gpu-layers 999 --host 0.0.0.0 --temp 1.0 --top-p 0.95 --top-k 64 --split-mode none --main-gpu 0 --flash-attn on 
  # qwen36-27b-base-q3:
  #   cmd: llama-server --port ${PORT} --model /models/unsloth/Qwen3.6-27B-GGUF/Qwen3.6-27B-Q3_K_S.gguf --n-gpu-layers 99 --ctx-size 131072 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64
  # qwen35-a3b-q4:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Qwen3.5-35B-A3B-GGUF/Qwen3.5-35B-A3B-Q4_K_M.gguf --n-gpu-layers 99 --ctx-size 131072 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64
  # qwen35-a3b-q6:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Qwen3.5-35B-A3B-GGUF/Qwen3.5-35B-A3B-Q6_K.gguf --n-gpu-layers 99 --ctx-size 131072 --host 0.0.0.0 --temp 0.1 --top-p 0.95 --top-k 64
  # qwen35-9b-q4:
  #   cmd: llama-server --port ${PORT} --model /models/lmstudio-community/Qwen3.5-9B-GGUF/Qwen3.5-9B-Q4_K_M.gguf --n-gpu-layers 99 --ctx-size 131072 --host 0.0.0.0  --temp 0.1 --top-p 0.95 --top-k 64 --split-mode none --main-gpu 1


routing:
  router:
    settings:
      groups: 
        "clever":
          # swap: false lets all members stay loaded at once
          swap: false
          # exclusive: false means requesting a member loads it without
          # unloading any other group
          exclusive: false
          members:
            - gemma31q4
            - gemma26
        # "code":
        #   # swap: false lets all members stay loaded at once
        #   swap: false
        #   # exclusive: false means requesting a member loads it without
        #   # unloading any other group
        #   exclusive: false
        #   members:
        #     - qwen36-27b-mtp-q3
        #     - gemma26